In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
#import dataset
dataset = pd.read_csv(r'D:\GitHub\Hands-on-Machine-Learning-Using-Python\1 Data Preprocessing\Data.csv')
X = dataset.iloc[:, :-1].values #take all rows, but exclude last column
Y = dataset.iloc[:, 3].values #take last column

In [12]:
dataset.head

<bound method NDFrame.head of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [13]:
dataset.shape

(10, 4)

In [14]:
dataset.index

RangeIndex(start=0, stop=10, step=1)

In [15]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [16]:
#Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


c:\users\shayan\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [17]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [23]:
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [24]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)


[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [26]:
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
np.set_printoptions(precision=2, suppress=True)
print(X)
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print(Y.reshape(-1,1))

[[     0.        1.        0.        0.       44.    72000.  ]
 [     1.        0.        0.        1.       27.    48000.  ]
 [     1.        0.        1.        0.       30.    54000.  ]
 [     1.        0.        0.        1.       38.    61000.  ]
 [     1.        0.        1.        0.       40.    63777.78]
 [     0.        1.        0.        0.       35.    58000.  ]
 [     1.        0.        0.        1.       38.78  52000.  ]
 [     0.        1.        0.        0.       48.    79000.  ]
 [     1.        0.        1.        0.       50.    83000.  ]
 [     0.        1.        0.        0.       37.    67000.  ]]
[[0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]


In [30]:
#Splitting the dataset in to training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
print("Train Set: ")
print(X_train)
print(Y_train.reshape(-1,1))

Train Set: 
[[     1.        0.        1.        0.       40.    63777.78]
 [     0.        1.        0.        0.       37.    67000.  ]
 [     1.        0.        0.        1.       27.    48000.  ]
 [     1.        0.        0.        1.       38.78  52000.  ]
 [     0.        1.        0.        0.       48.    79000.  ]
 [     1.        0.        0.        1.       38.    61000.  ]
 [     0.        1.        0.        0.       44.    72000.  ]
 [     0.        1.        0.        0.       35.    58000.  ]]
[[1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]


In [32]:
print("Test Set: ")
print(X_test)
print(Y_test.reshape(-1,1))

Test Set: 
[[     1.      0.      1.      0.     30.  54000.]
 [     1.      0.      1.      0.     50.  83000.]]
[[0]
 [0]]


In [33]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train)
print("\n")
print(X_test)
print("\n")

[[ 1.   -1.    2.65 -0.77  0.26  0.12]
 [-1.    1.   -0.38 -0.77 -0.25  0.46]
 [ 1.   -1.   -0.38  1.29 -1.98 -1.53]
 [ 1.   -1.   -0.38  1.29  0.05 -1.11]
 [-1.    1.   -0.38 -0.77  1.64  1.72]
 [ 1.   -1.   -0.38  1.29 -0.08 -0.17]
 [-1.    1.   -0.38 -0.77  0.95  0.99]
 [-1.    1.   -0.38 -0.77 -0.6  -0.48]]


[[ 1.   -1.    2.65 -0.77 -1.46 -0.9 ]
 [ 1.   -1.    2.65 -0.77  1.98  2.14]]


